# Generated by Django 2.1 on 2018-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180918_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
